language: rust

cache: cargo

sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose --no-default-features --features scott
  - cargo test --verbose --no-default-features --features parigot
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: nightly

after_success:
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
  cargo bench;
  cargo bench --no-default-features --features scott;
  cargo bench --no-default-features --features parigot;
  fi
